# -*- coding: utf-8 -*-
"""trail urban.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s4-vSJkUBN33IDaH7yAFwqMmXpQUWGw2
"""



T = float(input("Air Temperature at 2m (°C): "))
Td = float(input("Dew Point Temperature at 2m (°C): "))
RH = float(input("Relative Humidity (%) : "))
U_kmh = float(input("Wind Speed at 10m (km/h) : "))


U = U_kmh / 3.6
print(f"Wind Speed converted to m/s: {U:.2f} m/s")

delta_Td = T - Td
print(f"\nDew Point Depression (ΔTd): {delta_Td:.2f} °C")

RH_norm = max(0, min((RH - 95)/5, 1))
D_norm = max(0, min(1 - (delta_Td / 2), 1))
W_norm = max(0, min(1 - (U / 5), 1))

FDI = 0.4 * RH_norm + 0.4 * D_norm + 0.2 * W_norm
print(f"Fog Density Index (FDI): {FDI:.2f}")

if FDI < 0.3:
    visibility = "> 1000 m"
    condition = "Clear"
elif 0.3 <= FDI < 0.5:
    visibility = "500–1000 m"
    condition = "Light fog"
elif 0.5 <= FDI < 0.7:
    visibility = "200–500 m"
    condition = "Moderate fog"
elif 0.7 <= FDI < 0.9:
    visibility = "50–200 m"
    condition = "Dense fog"
else:
    visibility = "< 50 m"
    condition = "Very dangerous"

print(f"Estimated Visibility: {visibility}")
print(f"Driving Condition: {condition}")



